version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - CHROMA_PERSIST_DIR=/app/vector_db
      - DATA_PATH=/app/data/
    volumes:
      - ./patent_jsons_ML Assignment/patent_jsons:/app/data
      - ./vector_db:/app/vector_db
    restart: unless-stopped
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  # Load balancer for horizontal scaling
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
    restart: unless-stopped

volumes:
  vector_db:
    driver: local